### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by tianzhilan0** [LinXunFeng/transporter_fix#1]
lig@MacBook-Pro-3 ~ % /Users/lichuang/Downloads/transporter_fix ; exit;
下载文件
Traceback (most recent call last):
  File "urllib/request.py", line 1317, in do_open
  File "http/client.py", line 1229, in request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "http/client.py", line 1016, in _send_output
  File "http/client.py", line 956, in send
  File "http/client.py", line 1384, in connect
  File "http/client.py", line 928, in connect
  File "socket.py", line 727, in create_connection
  File "socket.py", line 716, in create_connection
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "utils/down_file.py", line 14, in download_from_url
  File "utils/down_file.py", line 12, in download_from_url
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 641, in http_response
  File "urllib/request.py", line 563, in error
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 755, in http_error_302
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1360, in https_open
  File "urllib/request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
[2866] Failed to execute script main

[进程已完成]

**Comment by LinXunFeng** [comment]
估计你当前环境没有科学上网，可以看一下 `README` 中的 [其它](https://github.com/LinXunFeng/transporter_fix#%E5%85%B6%E5%AE%83) 部分，下载 `com.apple.amp.itmstransporter.zip` 并存放到对应路径
